### ISSUE TITLE
Make `all_users` mockable

### ISSUE THREAD

**Issue by OLEGSHA** [rustadopt/uzers-rs#10]
As far as I can tell, there is currently no way to mock an `all_users` call.

I have encountered in my project a situation where the need to test code that makes use of `all_users` requires a lot of unwieldy refactoring. As such, I want to author a PR to add this functionality myself; however, I would like to get the maintainers' opinion first.

(The actual PR should address `all_groups` in a similar way, I will leave groups out of this discussion for brevity.)

---

# What should the new API look like?
As `all_users` is `unsafe`, I don't see a clear-cut solution without compromise. Here are some options I have come up with:

## Lazy getter
Add `unsafe fn Users.get_all_users() -> Option<Arc<impl Iterator<Item = User>>>`.
In `UsersCache`: returns an iterator over `cache`, except on first call, `all_users()` is called to ensure the cache is complete.

**Example usage:**
```rust
let mut myUsers = UsersCache::new();
let iter = unsafe { myUsers.get_all_users() }; // calls all_users()
for user in iter {
    println!("User #{} ({:?})", user.uid(), user.name());
}
let iter = unsafe { myUsers.get_all_users() }; // returns cache only
for user in iter {
    println!("User #{} ({:?})", user.uid(), user.name());
}
```
**Pros:**
- API stays homogeneous.

**Cons:**
- Since `all_users` is not thread-safe, every invocation of this method has to be checked for race conditions, making it essentially unusable in multithreaded environments.
- Inconsistencies may arise if `all_users()` returns data that conflicts with existing cache entries.

## New trait
There are currently two constructors for `UsersCache`: `new`, which does not fill the cache with all existing users, and `with_all_users`, which does. Caches returned by the latter can safely provide the full list of users. Let's "mark" these caches with a new trait, `UsersComplete`, that has a safe `fn get_all_users() -> Option<Arc<impl Iterator<Item = User>>>` (possibly even without `Arc`).

**Proposed API changes:**
- new trait `UsersComplete`
- new struct `UsersCacheComplete` that implements `Users` and `UsersComplete` and does not use syscalls at all
- change return type of `UsersCache::with_all_users` to `UsersCacheComplete`
- implement `UsersComplete` for `MockUsers`

**Example usage:**
```rust
fn foo<U: Users>(users: &mut U)
{ /* ... */ } // Does not iterate users

fn bar<U: Users + UsersComplete>(users: &mut U)
{ /*users.get_all_users().(...)*/ } // Iterates users

let lazyCache = UsersCache::new();
let eagerCache = unsafe { UsersCache::with_all_users() }; // the only possible all_users call
foo(lazyCache);
foo(eagerCache);
bar(eagerCache);
//bar(lazyCache); // Error: lazyCache cannot know all users
```
**Pros:**
- Explicitness

**Cons:**
- Modification of published method
- Eagerness

**Option:**
`UsersCache::with_all_users()` can be left as-is and a new `UsersCacheComplete::new` constructor can be introduced instead. This is even more explicit and guaranteed to not break compatibility, but it introduces a confusing duplicity.

**Comment by gierens** [comment]
Ui, thanks for the detailed proposal first of all ... took me a moment to grasp it ... I think we should generally strive to make this more safe so I'm leaning more towards option two, especially as we can also do this without modifying the API but just adding to it. As long as the difference between the methods is properly documented this shouldn't be too confusing, and if we really want to get rid of the old version we can put a `#[deprecated]` on it and remove it at some point in the future.
