### ISSUE TITLE
Add GECOS/comment field to User

### ISSUE THREAD

**Issue by apognu** [rustadopt/uzers-rs#12]
Right now, the `User` struct contains a few methods to get some common fields (UID, username) and some extra fields through OS-specific traits (home directory, shell, password).

One big missing field here would be the comment (or GECOS) field, which coudl sometimes contain the name of that user.

Would it be possible to add it where it makes sense (at least for UNIX targets)?

I can try and work on a PR if this is wanted.

**Comment by apognu** [comment]
This was also merged! Thank you. :)

**Comment by gierens** [comment]
I linked the PR to this issue so this auto-closes when the PR is merged ;)
