### ISSUE TITLE
Please cut a 0.12 release

### ISSUE THREAD

**Issue by samcday** [rustadopt/uzers-rs#21]
Thanks for maintaining this crate.

I discovered it when I went hunting for GECOS support in the upstream crate. I was then pleasantly surprised to find `uzers` and that @apognu had already implemented it (nice one! :+1:).

It'd be great if that support ended up in a tagged release so I don't have to pull this crate from git. Thanks in advance!

P.S: given that the `users` crate has been abandoned for quite a while, I wonder if ya'll have reached out to help@crates.io to take over ownership yet?

**Comment by gierens** [comment]
Will do! Thanks for bringing it up.

**Comment by gierens** [comment]
Done

**Comment by samcday** [comment]
Thanks kindly! :tada:
